name = "weeziq-ws-service"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Main entry point
main = "src/index.ts"

# Environment variables
[vars]
NODE_ENV = "production"

# Durable Objects for WebSocket connections and chat rooms
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "VISITOR_TRACKER"
class_name = "VisitorTracker"

# KV Namespace for storing visitor data and chat history
[[kv_namespaces]]
binding = "CHAT_STORAGE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 bucket for file storage (optional)
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "weeziq-files"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "VisitorTracker"]

# Environment variables (secrets)
# These need to be set via wrangler secret put
# - OPENAI_API_KEY
# - GOOGLE_AI_API_KEY
# - ALLOWED_ORIGINS
