name = "weeziq-ws-service"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Main entry point
main = "src/index.ts"

# Environment variables
[vars]
NODE_ENV = "production"

# Environment variables (secrets)
# These need to be set via wrangler secret put
# - OPENAI_API_KEY
# - GOOGLE_AI_API_KEY
# - ALLOWED_ORIGINS
