name = "weeziq-ws-service"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[durable_objects]
bindings = [
  { name = "CHATROOMS", class_name = "ChatRoomDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoomDurableObject"]

[env.production]
name = "weeziq-ws-service"

[env.staging]
name = "weeziq-ws-service-staging"
