name = "weeziq-ws-service"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Main entry point
main = "src/index.ts"

# Environment variables
[vars]
NODE_ENV = "production"

# Durable Objects for WebSocket connections and chat rooms
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "VISITOR_TRACKER"
class_name = "VisitorTracker"

# KV Namespace for storing visitor data and chat history
[[kv_namespaces]]
binding = "CHAT_STORAGE"
id = "db2d575a44a54673a3d680a480077288"
preview_id = "0f84fa40e273415abf246c92660cd7cf"



# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom", "VisitorTracker"]

# Environment variables (secrets)
# These need to be set via wrangler secret put
# - OPENAI_API_KEY
# - GOOGLE_AI_API_KEY
# - ALLOWED_ORIGINS
